In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\User\Desktop\Machine Learning\ML_Task_01\dataset_combined.csv")
print(df)

                                                  Path     Identity  \
0    C:\Users\User\Desktop\Machine Learning\Persona...  Hamza Ahmad   
1    C:\Users\User\Desktop\Machine Learning\Persona...  Hamza Ahmad   
2    C:\Users\User\Desktop\Machine Learning\Persona...  Hamza Ahmad   
3    C:\Users\User\Desktop\Machine Learning\Persona...  Hamza Ahmad   
4    C:\Users\User\Desktop\Machine Learning\Persona...  Hamza Ahmad   
..                                                 ...          ...   
194  C:\Users\User\Desktop\Machine Learning\Other\G...      Unknown   
195  C:\Users\User\Desktop\Machine Learning\Other\G...      Unknown   
196  C:\Users\User\Desktop\Machine Learning\Other\G...      Unknown   
197  C:\Users\User\Desktop\Machine Learning\Other\G...      Unknown   
198  C:\Users\User\Desktop\Machine Learning\Other\G...      Unknown   

      Expression  Age  
0        Smiling   23  
1    Not Smiling   23  
2    Not Smiling   23  
3        Smiling   23  
4    Not Smiling   23  
.. 

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split


train, test = train_test_split(df, test_size=0.3, random_state = 8)

In [3]:
train.loc[train['Age'] == 23].describe()

Age
count  73.0
mean   23.0
std     0.0
min    23.0
25%    23.0
50%    23.0
75%    23.0
max    23.0

In [4]:
train.loc[train['Age'] != 23].describe() 
#stratifed split is successful

Age
count  66.000000
mean   58.136364
std    17.951976
min    12.000000
25%    46.000000
50%    59.500000
75%    72.000000
max    99.000000

In [5]:
X_data = train['Path']
X_tdata = test['Path']
y1_train = train['Identity']
y2_train = train['Expression']
y3_train = train['Age']
y1_test = test['Identity']
y2_test = test['Expression']
y3_test = test['Age']

In [6]:
X_data

182    C:\Users\User\Desktop\Machine Learning\Other\F...
113    C:\Users\User\Desktop\Machine Learning\Other\A...
79     C:\Users\User\Desktop\Machine Learning\Persona...
142    C:\Users\User\Desktop\Machine Learning\Other\C...
188    C:\Users\User\Desktop\Machine Learning\Other\G...
                             ...                        
136    C:\Users\User\Desktop\Machine Learning\Other\C...
133    C:\Users\User\Desktop\Machine Learning\Other\B...
105    C:\Users\User\Desktop\Machine Learning\Other\A...
84     C:\Users\User\Desktop\Machine Learning\Persona...
195    C:\Users\User\Desktop\Machine Learning\Other\G...
Name: Path, Length: 139, dtype: object

In [7]:
import skimage
from skimage import io
from skimage import transform

lst = []
for path in X_data:
    curr_image = io.imread(path)
    img_resize = transform.resize(curr_image, output_shape=(32,32,3)) #resize image to match a certain type
    img_reshape = np.reshape(img_resize, (32*32*3))
    lst.append(img_reshape/255.)
    
X_train = np.array(lst)
print(X_train)

[[0.00020528 0.00021926 0.00024333 ... 0.00062626 0.00068319 0.00088945]
 [0.00118929 0.00121232 0.00106665 ... 0.00080002 0.00084119 0.00091485]
 [0.00223232 0.00152865 0.00110605 ... 0.00096045 0.00081889 0.00078292]
 ...
 [0.00133537 0.00099903 0.00115933 ... 0.00213558 0.00232012 0.00253542]
 [0.0006189  0.00088462 0.00140921 ... 0.00023611 0.00023125 0.00039626]
 [0.00024174 0.00024354 0.0002437  ... 0.00065935 0.00061324 0.00053635]]


In [8]:
X_train.ndim #Image dimensions after resizing

2

In [9]:
lst = []
for path in X_tdata:
    curr_image = io.imread(path)
    img_resize = transform.resize(curr_image, output_shape=(32,32,3))
    img_reshape = np.reshape(img_resize, (32*32*3))
    lst.append(img_reshape/255.)
    
X_test = np.array(lst)
print(X_test)

[[0.00372479 0.0036633  0.00364792 ... 0.00092841 0.00082061 0.00067896]
 [0.00369036 0.00335115 0.00285218 ... 0.0009648  0.00092806 0.00090443]
 [0.00148349 0.00128357 0.00114516 ... 0.00103969 0.0008479  0.00067647]
 ...
 [0.0006255  0.00047171 0.00045633 ... 0.00056502 0.00045768 0.00056406]
 [0.00270232 0.00256153 0.00237478 ... 0.00047237 0.00053545 0.00058865]
 [0.00389981 0.00390084 0.00388917 ... 0.00392059 0.00392001 0.0039204 ]]


In [10]:
X_test.shape

(60, 3072)

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import joblib

#initialize the linear regression model
model = LinearRegression()
model.fit(X_train, y3_train)

# Save the trained model to a file
joblib.dump(model, 'linear_regression_model.pkl')
#we can load this model using joblib.load


# Print the learned regression coefficients
print("Regression Coefficients: ", model.coef_)
#training the model
y_pred = model.predict(X_test)

mse = mean_squared_error(y3_test, y_pred)
r2 = r2_score(y3_test, y_pred)
print("MSE: ", mse)
print("R Squared Error:", r2)

Regression Coefficients:  [-365.23015806 -313.61622687 -307.80822033 ...   69.79053237  150.693183
  134.05577014]
MSE:  581.0247707301312
R Squared Error: -0.11954957372567909


In [12]:
model.score(X_train, y3_train) #uses R Squared Metric to compute score for training data
#helps us determine that model is overfitting

1.0